version: '3'

services:
  serverbot:
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_SERVER: ${DISCORD_SERVER}
    image: serverbot
    build:
      context: .
      dockerfile: ./Dockerfile
